### ISSUE TITLE
Add support for the stm32f407vg

### ISSUE THREAD

**Issue by jkristell** [Disasm/usb-otg-workspace#2]
Hi

I extended and tested the code in your repo with the stm32f407g-disc1 board and verified that it worked. Really nice to be able to use the USB on this board as well!

If you want to add this board to your examples as well I can put together a pull request to this project , and to your fork of the stm32f4xx-hal?

**Comment by Disasm** [comment]
Hi! Feel free to PR your example to this repo. As for the `stm32f4xx-hal`, it's better to upstream relevant changes. If you only need to enable `usb` module for this chip, you can PR this change to my fork.
