### ISSUE TITLE
How to properly test 'serial' example? (NucleoF429ZI)

### ISSUE THREAD

**Issue by JOE1994** [Disasm/usb-otg-workspace#4]
First of all, thank you so much for sharing your hard work! :cat: 

I'm having some trouble testing the `serial` example with my `NucleoF429ZI` board
(I'm a noob in embedded systems :crying_cat_face: ).

I properly initialized `vid` & `pid` from `lsusb` output. 
I used `minicom` to connect to `ttyACM0`, and typed a bunch of lowercase letters from minicom.
I expected to see uppercase letters echoed back, but couldn't see anything printed on my `minicom` screen.

May I ask how you successfully tested the `serial` example on the `NucleoF429ZI` board?

Thank you so much :+1:

**Comment by Disasm** [comment]
Hmm, that's strange. Could you try the same with `screen /dev/ttyACM1 115200`? Also check that you build the firmware with `--release`.

I usually only do stress testing with https://github.com/mvirkkunen/serial-threadmark

**Comment by Disasm** [comment]
Also `/dev/ttyACM0` can be used by on-board STLINK programmer, check that you use the one from the serial USB

**Comment by JOE1994** [comment]
> Also `/dev/ttyACM0` can be used by on-board STLINK programmer, check that you use the one from the serial USB

When I run `$ ls /dev/tty*`, other than bunch of `/dev/ttyS*`s, I can only find `/dev/ttyACM0` and nothing else :crying_cat_face:.
Running the `screen` utility doesn't work for me either.

I currently only have one USB cable connected to my board.
When testing the example, did you have any additional wire connections from the board to your pc ?

**Comment by Disasm** [comment]
I use two cables: one connected to the onboard stlink and another one connected to the microUSB connector on the opposite side of the board. I don't know why, but if I connect only the second one, the board is not powered and doesn't work.

**Comment by JOE1994** [comment]
> I use two cables: one connected to the onboard stlink and another one connected to the microUSB connector on the opposite side of the board. I don't know why, but if I connect only the second one, the board is not powered and doesn't work.

It works now! :smiley: After connecting the second cable, I can see `/dev/ttyACM1` and the https://github.com/mvirkkunen/serial-threadmark works as expected! Thank you so much for your help :+1:  You saved my day!
